<i>## Comments will be provided using this format. Key takeaway: groups are encouraged to change the formatting, but not the structure. Groups are also allowed to create additional notebooks - for instance, create one notebook for data exploration, and one notebook for each preprocessing-modelling-evaluation pipeline -, but must strive to keep an unified style across notebooks.</i>

#### NOVA IMS / BSc in Data Science / Text Mining 2025/2026
### <b>Group Project: "Straining the great southern Melting Pot"</b>
#### Notebook `Notebook Title`

#### Group:
- `Group member #1`
- `(...)`
- `Group member #5`

#### <font color='#BFD72'>Table of Contents </font> <a class="anchor" id='toc'></a> 
- [1. Data Understanding](#P1)
- [2. General Data Preparation](#P2) 
- [3. Multilabel Classification (Information Requirement 3311)](#P3)
    - [3.1 Specific Data Preparation](#P31)
    - [3.2 Model Implementation](#P32)
    - [3.3 Model Evaluation](#P3n)
- [4. Sentiment Analysis (Information Requirement 3312)](#P4)
    - [4.1 Specific Data Preparation](#P41)
    - [4.2 Model Implementation](#P42)
    - [4.3 Model Evaluation](#P43)
- [...]
- [N. Additional Tasks (Information Requirements 332n)](#Pn)
    - [N.1 Specific Data Preparation](#Pn1)
    - [N.2 Model Implementation](#Pn2)
    - [N.3 Model Evaluation](#Pn3)

<i>## Note that the notebook structure differs from the report: instead of following the CRISP-DM phases and then specifying the different problems inside the phases, the notebook is structured by problem, with the CRISP-DM phases being defined for each specific problem.

In [1]:
## All imports must be concentrated on a cell that immediately follow the table of contents
import time
import pandas as pd

<font color='#BFD72F' size=5>1. Data Understanding</font> <a class="anchor" id="P1"></a>
  
[Back to TOC](#toc)

<i>## Use markdown cells to describe the purpose of the code cells that follow them.</i>

Let's start buy reading the dataset

In [2]:
## Functions must be defined on separate cells
def text_mining_project_simulator():
    project_progress = 0
    while project_progress < 100:
        ## Comments on code cells can be used to highlight specific sections of yout code
        project_progress += 1
        print("working, albeit reluctantly, on a project that's {}% done \n\n".format(project_progress))
        time.sleep(5)

In [ ]:
## Calls to functions (whether defined by the group, or imported from packages) must be separate from their definition

text_mining_project_simulator()

<font color='#BFD72F' size=5>2. Data Preprocessing</font> <a class="anchor" id="P1"></a>
  
[Back to TOC](#toc)

<i>## Use markdown cells to describe the purpose of the code cells that follow them.</i>

In [23]:
import pandas as pd
import re
import unicodedata
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [2]:
atlanta_rest = pd.read_csv("data_atlanta/atlanta_restaurant_slice_2023.csv", header=0)
atlanta_rest

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...
...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Friday night dinner was Chicken Francaise. Jor...
53562,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great dinner.... Yay Jordan!!!!!!
53563,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was our server and he was fantastic! Gr...
53564,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was an amazing server! Great delicious...
53565,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great food and service. Well spaced tables a...

In [3]:
atlanta_rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

In [4]:
# Drop duplicates and rows without review text
atlanta_rest.drop_duplicates(subset=["text"], inplace=True)
atlanta_rest.dropna(subset=["text"], inplace=True)

In [5]:
# Drop the unneeded columns, rename the 'text' column to 'raw_text', and change its data type to 'string'.
atlanta_rest = atlanta_rest.drop(columns=["website","url"])
atlanta_rest = atlanta_rest.rename(columns={"text":"raw_content"})
atlanta_rest["raw_content"] = atlanta_rest["raw_content"].astype(str)
atlanta_rest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51542 entries, 0 to 53565
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         51542 non-null  object
 1   categoryName  51542 non-null  object
 2   reviewsCount  51542 non-null  int64
 3   stars         51542 non-null  float64
 4   raw_content   51542 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.4+ MB

In [6]:
atlanta_rest.sample(5)

,title,categoryName,reviewsCount,stars,raw_content
3591,La Parrilla Mexican Restaurant,Mexican restaurant,328,4.0,"95% of STAFF Is The BEST, VERY VERY Low Turn Over"
9017,Shake Shack Perimeter Mall,Hamburger restaurant,1900,3.0,It was just ok. The food reminded me of Steak ...
5367,Milano Pizza & Subs,Pizza restaurant,300,5.0,First time but will be returning! I'm a Jersey...
44603,Night Life Pizza,Italian restaurant,730,5.0,Love that it opens late
17473,CAVA,Mediterranean restaurant,451,5.0,"Real great place, foods great, nice and clean,..."

In [7]:
print("Columns after cleaning:", atlanta_rest.columns.tolist())

Columns after cleaning: ['title', 'categoryName', 'reviewsCount', 'stars', 'raw_content']

In [8]:
import re

# Regex pattern for emojis
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags=re.UNICODE)

# Function to extract emojis from a text
def extract_emojis(text):
    return emoji_pattern.findall(str(text))

# Apply extraction temporarily (no new column)
emoji_reviews = [(i, txt, extract_emojis(txt)) 
                 for i, txt in enumerate(atlanta_rest["raw_content"]) 
                 if extract_emojis(txt)]

# Display the number of reviews that contain emojis
print(f"Number of reviews with emojis: {len(emoji_reviews)}")

# Optionally show the first few examples
for i, txt, emojis in emoji_reviews[:10]:
    print(f"\nReview #{i}: {emojis}\n{txt[:200]}...")

Number of reviews with emojis: 0

In [9]:
# Check and count accents, symbols, and emojis in the reviews
accent_pattern = re.compile(r"[^\x00-\x7F]")  # detects non-ASCII (accents & special Unicode)
symbol_pattern = re.compile(r"[\u2600-\u26FF\u2700-\u27BF]")  # symbols, dingbats
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map
                           u"\U0001F1E0-\U0001F1FF"  # flags
                           "]+", flags=re.UNICODE)

def has_accent(text):
    return bool(accent_pattern.search(str(text)))

def has_symbol(text):
    return bool(symbol_pattern.search(str(text)))

def has_emoji(text):
    return bool(emoji_pattern.search(str(text)))

# Checks and counts
atlanta_rest["has_accent"] = atlanta_rest["raw_content"].apply(has_accent)
atlanta_rest["has_symbol"] = atlanta_rest["raw_content"].apply(has_symbol)
atlanta_rest["has_emoji"] = atlanta_rest["raw_content"].apply(has_emoji)

print("Accents:", atlanta_rest["has_accent"].sum(), f"({atlanta_rest['has_accent'].mean():.2%})")
print("Symbols:", atlanta_rest["has_symbol"].sum(), f"({atlanta_rest['has_symbol'].mean():.2%})")
print("Emojis:", atlanta_rest["has_emoji"].sum(), f"({atlanta_rest['has_emoji'].mean():.2%})")

Accents: 7434 (14.42%)
Symbols: 355 (0.69%)
Emojis: 0 (0.00%)

In [10]:
def clean_text(text):
    """
    Basic text cleaning:
    - lowercasing
    - remove URLs, HTML, mentions, hashtags
    - remove non-letter characters and extra spaces
    """
    text = str(text).lower()                          # Lowercase
    text = re.sub(r"http\S+|www\S+", "", text)        # Remove URLs
    text = re.sub(r"<.*?>", "", text)                 # Remove HTML tags
    text = re.sub(r"@\w+", "", text)                  # Remove @mentions
    text = re.sub(r"#\w+", "", text)                  # Remove hashtags
    text = re.sub(r"[^a-z\s]", " ", text)             # Keep letters only
    text = re.sub(r"\s+", " ", text).strip()          # Remove extra spaces
    text = unicodedata.normalize('NFKD', text)        # Normalize unicode
    text = text.encode('ascii', 'ignore').decode('utf-8')
    punctuation_pattern = r"[\u0021-\u002F\u003A-\u003F\u005B-\u005F\u2010-\u2028]+" # Remove punctuation
    text = re.sub(punctuation_pattern, " ", text)
    
    text = re.sub(r"[^a-z\s]", " ", text)       # Keep letters only (remove emojis and special symbols)
    return text

In [11]:
# Apply the cleaning function
atlanta_rest["clean_text"] = atlanta_rest["raw_content"].apply(clean_text)

In [12]:
atlanta_rest

,title,categoryName,reviewsCount,stars,raw_content,has_accent,has_symbol,has_emoji,clean_text
0,The Optimist,Seafood restaurant,3349,5.0,"One word amazing!! The red fish, halibut, fr...",False,False,False,one word amazing the red fish halibut fried ri...
1,The Optimist,Seafood restaurant,3349,5.0,First time here and the food is great and the ...,False,False,False,first time here and the food is great and the ...
2,The Optimist,Seafood restaurant,3349,5.0,I recently had the pleasure of dining at Optim...,False,False,False,i recently had the pleasure of dining at optim...
3,The Optimist,Seafood restaurant,3349,5.0,Beautiful atmosphere and delicious food. All o...,True,False,False,beautiful atmosphere and delicious food all of...
4,The Optimist,Seafood restaurant,3349,5.0,We had a wonderful dinner at the Optimist. Our...,False,False,False,we had a wonderful dinner at the optimist our ...
...,...,...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,449,5.0,Friday night dinner was Chicken Francaise. Jor...,False,False,False,friday night dinner was chicken francaise jord...
53562,L On North,New American restaurant,449,5.0,Great dinner.... Yay Jordan!!!!!!,False,False,False,great dinner yay jordan
53563,L On North,New American restaurant,449,5.0,Jordan was our server and he was fantastic! Gr...,False,False,False,jordan was our server and he was fantastic gre...
53564,L On North,New American restaurant,449,5.0,Jordan was an amazing server! Great delicious...,False,False,False,jordan was an amazing server great delicious m...
53565,L On North,New American restaurant,449,5.0,Great food and service. Well spaced tables a...,False,False,False,great food and service well spaced tables and ...

Tokenisation

In [16]:
nltk.download('punkt_tab')
atlanta_rest["tokenised_content"] = atlanta_rest["clean_text"].apply(word_tokenize)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/cyrinemoalla/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [21]:
nltk.download('averaged_perceptron_tagger_eng')
atlanta_rest['pos_tags'] = atlanta_rest['tokenised_content'].apply(lambda tokens : [pos[1] for pos in pos_tag(tokens)])

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/cyrinemoalla/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [22]:
atlanta_rest

,title,categoryName,reviewsCount,stars,raw_content,has_accent,has_symbol,has_emoji,clean_text,tokenised_content,pos_tags
0,The Optimist,Seafood restaurant,3349,5.0,"One word amazing!! The red fish, halibut, fr...",False,False,False,one word amazing the red fish halibut fried ri...,"[one, word, amazing, the, red, fish, halibut, ...","[CD, NN, VBG, DT, JJ, NN, NN, VBD, NN, CC, NN,..."
1,The Optimist,Seafood restaurant,3349,5.0,First time here and the food is great and the ...,False,False,False,first time here and the food is great and the ...,"[first, time, here, and, the, food, is, great,...","[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ..."
2,The Optimist,Seafood restaurant,3349,5.0,I recently had the pleasure of dining at Optim...,False,False,False,i recently had the pleasure of dining at optim...,"[i, recently, had, the, pleasure, of, dining, ...","[NN, RB, VBD, DT, NN, IN, VBG, IN, NN, IN, JJ,..."
3,The Optimist,Seafood restaurant,3349,5.0,Beautiful atmosphere and delicious food. All o...,True,False,False,beautiful atmosphere and delicious food all of...,"[beautiful, atmosphere, and, delicious, food, ...","[NN, RB, CC, JJ, NN, DT, IN, DT, NN, NN, NN, I..."
4,The Optimist,Seafood restaurant,3349,5.0,We had a wonderful dinner at the Optimist. Our...,False,False,False,we had a wonderful dinner at the optimist our ...,"[we, had, a, wonderful, dinner, at, the, optim...","[PRP, VBD, DT, JJ, NN, IN, DT, JJ, PRP$, NN, I..."
...,...,...,...,...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,449,5.0,Friday night dinner was Chicken Francaise. Jor...,False,False,False,friday night dinner was chicken francaise jord...,"[friday, night, dinner, was, chicken, francais...","[JJ, NN, NN, VBD, VBN, RB, NN, VBD, DT, JJ, NN..."
53562,L On North,New American restaurant,449,5.0,Great dinner.... Yay Jordan!!!!!!,False,False,False,great dinner yay jordan,"[great, dinner, yay, jordan]","[JJ, NN, NNS, NN]"
53563,L On North,New American restaurant,449,5.0,Jordan was our server and he was fantastic! Gr...,False,False,False,jordan was our server and he was fantastic gre...,"[jordan, was, our, server, and, he, was, fanta...","[NN, VBD, PRP$, NN, CC, PRP, VBD, JJ, JJ, NN]"
53564,L On North,New American restaurant,449,5.0,Jordan was an amazing server! Great delicious...,False,False,False,jordan was an amazing server great delicious m...,"[jordan, was, an, amazing, server, great, deli...","[NN, VBD, DT, JJ, NN, JJ, JJ, NN, CC, VB, JJ, ..."
53565,L On North,New American restaurant,449,5.0,Great food and service. Well spaced tables a...,False,False,False,great food and service well spaced tables and ...,"[great, food, and, service, well, spaced, tabl...","[JJ, NN, CC, NN, RB, JJ, NNS, CC, JJ, NN, MD, ..."

Remove Stopwords

In [25]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def normalise_tokens(tokens):
    tokens = [t for t in tokens if t.isalpha()]                # keep words only
    tokens = [t for t in tokens if t not in stop_words]        # remove stopwords
    tokens = [lemmatizer.lemmatize(t) for t in tokens]         # lemmatise
    return tokens

atlanta_rest["norm_tokens"] = atlanta_rest["tokenised_content"].apply(normalise_tokens)
atlanta_rest["processed_text"] = atlanta_rest["norm_tokens"].apply(lambda x: " ".join(x))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/cyrinemoalla/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/cyrinemoalla/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/cyrinemoalla/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [26]:
atlanta_rest['norm_tokens']

0        [one, word, amazing, red, fish, halibut, fried...
1            [first, time, food, great, waiter, excellent]
2        [recently, pleasure, dining, optimist, atlanta...
3        [beautiful, atmosphere, delicious, food, food,...
4        [wonderful, dinner, optimist, group, great, me...
                               ...
53561    [friday, night, dinner, chicken, francaise, jo...
53562                         [great, dinner, yay, jordan]
53563             [jordan, server, fantastic, great, meal]
53564    [jordan, amazing, server, great, delicious, me...
53565    [great, food, service, well, spaced, table, li...
Name: norm_tokens, Length: 51542, dtype: object